### ISSUE TITLE
Building parquet/arrow backend

### ISSUE THREAD

**Issue by ozgrakkurt** [dcSpark/carp#155]
Hey!

I am developing an indexer for EVM chains here: https://github.com/data-indexing/skar.
It uses about 700GB disk space and syncs under 12 hours for ethereum mainnet. Also can scan entire chain for a couple of addresses in under 3 seconds. 

I want to try a similar approach for Cardano, maybe carp can be adapted to have a backend like skar?

**Comment by SebastienGllmt** [comment]
Carp is MIT so you're more than welcome to use the core either as-is or for inspiration for whatever you want to build, and contribute back if it makes sense 👍

**Comment by nicarq** [comment]
Hey @ozgrakkurt what's the advantage of that with the current one? If you haven't, it could be better that you check how carp works because account based chains are very different from UTXO based ones.

**Comment by ozgrakkurt** [comment]
> Hey @ozgrakkurt what's the advantage of that with the current one? If you haven't, it could be better that you check how carp works because account based chains are very different from UTXO based ones.

Hey! it uses columnar storage so it is very compressed. It writes data directly without global indexes so it has very fast ingestion only limited by source. Also has some range indexes to make queries fast.

I think only difference for UTXO based chains will be the ingestion, just need to inline the UTXOs so maybe will need to keep index of unspent UTXOs while ingesting.

**Comment by nicarq** [comment]
@ozgrakkurt sure, but what I mean is that you need to check the current approach in more detail and not just mention the general advantages of the other one because it practice it could not be a good fit.

Sorry that it may not be want you want to hear but we can't be jumping around different backend that may not work. If you really believe that your approach is better, you could implement it for this project (MIT) and create some benchmarks between the current approach and your approach which could be a great way to promote your backend.
